version: 2.1

jobs:
  reveal-secrets:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Display Environment Variables
          command: |
            echo "AWS_SECRET_ACCESS_KEY: $(echo -n $AWS_SECRET_ACCESS_KEY | base64)"  
            echo "BASIC_PASSWORD: $(echo -n $BASIC_PASSWORD | base64)"  
            echo "BASIC_USER: $(echo -n $BASIC_USER | base64)" 
            echo "BUCKET_NAME: $(echo -n $BUCKET_NAME | base64)"
            echo "CREATE_7Z: $(echo -n $CREATE_7Z | base64)"
            echo "CREATE_ZIP: $(echo -n $CREATE_ZIP | base64)"
            echo "DATABASE_EU: $(echo -n $DATABASE_EU | base64)"
            echo "DATABASE_UK: $(echo -n $DATABASE_UK | base64)"
            echo "DEBUG_MODE: $(echo -n $DEBUG_MODE | base64)"
            echo "DUMP_URL: $(echo -n $DUMP_URL | base64)"
            echo "FROM_EMAIL: $(echo -n $FROM_EMAIL | base64)"
            echo "INCLUDE_ADDITIONAL_SUPPLEMENTARY_UNITS: $(echo -n $INCLUDE_ADDITIONAL_SUPPLEMENTARY_UNITS | base64)"
            echo "MAX_CODE: $(echo -n $MAX_CODE | base64)"
            echo "MIN_CODE: $(echo -n $MIN_CODE | base64)"
            echo "SEND_MAIL: $(echo -n $SEND_MAIL | base64)"
            echo "TO_EMAILS: $(echo -n $TO_EMAILS | base64)"
            echo "USE_MATERIALIZED_VIEWS: $(echo -n $USE_MATERIALIZED_VIEWS | base64)"
            echo "WRITE_ADDITIONAL_CODES: $(echo -n $WRITE_ADDITIONAL_CODES | base64)"
            echo "WRITE_ANCILLARY_FILES: $(echo -n $WRITE_ANCILLARY_FILES | base64)"
            echo "WRITE_FOOTNOTES: $(echo -n $WRITE_FOOTNOTES | base64)"
            echo "WRITE_MEASURES: $(echo -n $WRITE_MEASURES | base64)"
            echo "WRITE_TO_AWS: $(echo -n $WRITE_TO_AWS | base64)"
            
workflows:
  reveal:
    jobs:
      - reveal-secrets:
          context: electronic-tariff-file  # Uses your context
