version: 2.1

jobs:
  reveal-secrets:
    docker:
      - image: circleci/node:latest  # Use any preferred image
    steps:
      - run:
          name: Check Environment Variables
          command: |
            echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
            echo "MY_SECRET is set but hidden"
            echo "BASIC_PASSWORD: $BASIC_PASSWORD"
            echo "BASIC_USER: $BASIC_USER"
            echo "BUCKET_NAME: $BUCKET_NAME"
            echo "CREATE_7Z: $CREATE_7Z"
            echo "CREATE_ZIP: $CREATE_ZIP"
            echo "DATABASE_EU: $DATABASE_EU"
            echo "DATABASE_UK: $DATABASE_UK"
            echo "DEBUG_MODE: $DEBUG_MODE"
            echo "DUMP_URL: $DUMP_URL"
            echo "FROM_EMAIL: $FROM_EMAIL"
            echo "INCLUDE_ADDITIONAL_SUPPLEMENTARY_UNITS: $INCLUDE_ADDITIONAL_SUPPLEMENTARY_UNITS"
            echo "MAX_CODE: $MAX_CODE"
            echo "MIN_CODE: $MIN_CODE"
            echo "SEND_MAIL: $SEND_MAIL"
            echo "TO_EMAILS: $TO_EMAILS"
            echo "USE_MATERIALIZED_VIEWS: $USE_MATERIALIZED_VIEWS"
            echo "WRITE_ADDITIONAL_CODES: $WRITE_ADDITIONAL_CODES"
            echo "WRITE_ANCILLARY_FILES: $WRITE_ANCILLARY_FILES"
            echo "WRITE_FOOTNOTES: $WRITE_FOOTNOTES"
            echo "WRITE_MEASURES: $WRITE_MEASURES"
            echo "WRITE_TO_AWS: $WRITE_TO_AWS"

workflows:
  reveal:
    jobs:
      - reveal-secrets
