name: Thursday workflow

on:
  schedule:
    - cron: '00 07 * * 4' # Every Thursday around 08:30
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  IAM_ROLE_ARN: arn:aws:iam::382373577178:role/GithubActions-ETF-Role
  SECRET_NAME: electronic-tariff-file-configuration
  DEBUG_MODE: 0
  SEND_MAIL: 1

jobs:
  generate-electronic-tariff-file:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    -  uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        key: deps-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.in') }}
        path: |
          ~/.cache/pip
          venv

    - name: Install pip-tools and dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip==25.0.1 pip-tools
        # Check if requirements.in exists, if not use requirements.txt directly
        if [ -f "requirements.in" ]; then
          pip-compile --generate-hashes --output-file=requirements.txt requirements.in
          pip-sync requirements.txt
        fi
        pip install -r requirements.txt
        sudo apt-get update && sudo apt-get install -y jq postgresql-client wget

    - name: Fetch Secrets from AWS Secrets Manager
      uses: trade-tariff/trade-tariff-tools/.github/actions/fetch-secrets@main
      with:
        secret-name: ${{ env.SECRET_NAME }}

    - name: Prepare database
      shell: bash
      run: |
        source .env
        createdb -h localhost -U postgres electronic_tariff_file
        curl --silent -o- "$DUMP_URL" | gunzip | psql -h localhost -U postgres electronic_tariff_file

    - name:  Production run and send emails
      shell: bash
      run: |
        source venv/bin/activate
        source .env
        python create.py uk

  notifications:
      runs-on: ubuntu-latest
      needs: generate-electronic-tariff-file
      if: always()
      steps:
        - uses: actions/checkout@v4
        - uses: trade-tariff/trade-tariff-tools/.github/actions/slack-notify@main
          with:
            result: ${{ needs.generate-electronic-tariff-file.result }}
            slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
